server:
  shutdown: graceful
  port: 8080

spring:
  config:
    import:
      - security/application-db.yml
      - security/application-naver.yml
      - security/application-s3.yml
      - security/application-security.yml
      - security/application-swagger.yml