name: Java CI/CD with Gradle and S3

on:
  push:
    branches: [ "main" ]
    paths:
      - "batch/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACTION_SCRET_TOKEN }}  # Personal Access Token
          submodules: true  # Enable submodule checkout

      # Additional steps for Java and Gradle setup
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x batch/gradlew

      - name: Build with Gradle Wrapper
        run: ./batch/gradlew :batch:build

  delivery:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_SCRET_TOKEN }}  # Personal Access Token
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./batch/gradlew

      - name: Build with Gradle Wrapper
        run: ./batch/gradlew :batch:build

      - name: Build Docker image
        run: docker build -t likelion-batch batch

      - name: Save Docker image as tar
        run: docker save likelion-batch -o likelion-batch.tar

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 cp likelion-batch.tar s3://${{ secrets.S3_BUCKET_NAME }}/likelion-batch.tar


  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BATCH_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo docker stop $(sudo docker ps -a -q) || true
            sudo docker rm $(sudo docker ps -a -q) || true
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/likelion-batch.tar likelion-batch.tar
            sudo docker load -i likelion-batch.tar
            sudo docker run -d --log-driver=syslog --net mybridge -p 8080:8080 likelion-batch
            sudo docker image prune -a -f
