name: Java CI/CD with Gradle and S3

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACTION_SCRET_TOKEN }}  # Personal Access Token
          submodules: true  # Enable submodule checkout

      # Additional steps for Java and Gradle setup
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build