name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_SECRET_TOKEN }}  # Personal Access Token
          submodules: true  # Enable submodule checkout
          clean: true  # Ensure the repository is cleaned before checking out

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
