name: Java CI/CD with Gradle and S3

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACTION_SCRET_TOKEN }}  # Personal Access Token
          submodules: true  # Enable submodule checkout

      # Additional steps for Java and Gradle setup
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  delivery:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_SCRET_TOKEN }}  # Personal Access Token
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t likelion .

      - name: Save Docker image as tar
        run: docker save likelion -o likelion.tar

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 cp likelion.tar s3://${{ secrets.S3_BUCKET_NAME }}/likelion.tar

      - name: Pull Redis Docker image
        run: docker pull redis

      - name: Save Docker image as tar
        run: docker save redis -o redis.tar

      - name : add permision to redis.tar
        run : sudo chmod 777 redis.tar

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 cp redis.tar s3://${{ secrets.S3_BUCKET_NAME }}/redis.tar

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/redis.tar redis.tar
            sudo docker load -i redis.tar
            sudo docker stop $(sudo docker ps -a -q) || true
            sudo docker rm $(sudo docker ps -a -q) || true
            sudo docker run -d --log-driver=syslog --name redis --net mybridge -p 6379:6379 redis --requirepass "omeb4417"
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/likelion.tar likelion.tar
            sudo docker load -i likelion.tar
            sudo docker run -d --log-driver=syslog --net mybridge -p 8080:8080 likelion
            sudo docker image prune -a -f
